//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bascket
    {
        public int IdBascket { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> CodeHotel { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
