//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelInformation()
        {
            this.HotelPhotos = new HashSet<HotelPhotos>();
            this.HotelRooms = new HashSet<HotelRooms>();
            this.HotelsRating = new HashSet<HotelsRating>();
            this.ToursReg = new HashSet<ToursReg>();
        }
    
        public int IdHotel { get; set; }
        public string HotelName { get; set; }
        public string HotelCountry { get; set; }
        public string ResortTitle { get; set; }
        public string HotelDescription { get; set; }
        public string HotelStar { get; set; }
        public string TypeFood { get; set; }
        public string HotelServices { get; set; }
        public int HotelRating { get; set; }
        public string Services { get; set; }
        public string MainPhotoDirectory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPhotos> HotelPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelRooms> HotelRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelsRating> HotelsRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToursReg> ToursReg { get; set; }
    }
}
