//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourOperator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaidServices()
        {
            this.ToursReg = new HashSet<ToursReg>();
        }
    
        public int IdPaidServices { get; set; }
        public int IdClient { get; set; }
        public int IdIncuranceService { get; set; }
        public int IdCarrierService { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ServicesCarrierCompany ServicesCarrierCompany { get; set; }
        public virtual ServicesInsuranceCompany ServicesInsuranceCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToursReg> ToursReg { get; set; }
    }
}
